from selenium import webdriver
driver = webdriver.Chrome("E:\python_project\First_task\Scenario\chromedriver.exe")
driver.get("https://shopster.ai/en/app/dashboard/")
driver.get("https://shopster.ai/en/login/")
driver.find_element_by_xpath("//input[@placeholder='Username']").send_keys("shopstertest")
driver.find_element_by_xpath("//input[@placeholder='Password']").send_keys("shopster123!")
driver.find_element_by_xpath("//button[text()='Log into Shopster']").click()
driver.find_element_by_xpath("//div[text()='Store']").click()
# driver.find_element_by_xpath("//i[text()='add']").click()
driver.find_element_by_xpath("//span[text()='Categories']").click()
driver.find_element_by_xpath("//i[text()='add']").click()
driver.find_element_by_xpath("//input[@placeholder='Cookie']").send_keys("Cold_items")
driver.find_element_by_xpath("//input[@id='id_icon']").send_keys(r"C:\Users\Amaresh\Downloads\Multi.jpg")
driver.find_element_by_xpath("//span[@id='save']").click()
# driver.find_element_by_xpath("//a[@class='custom-link']/descendant::li[@class='store-menu-item']/descendant::span[text()='Categories']").click()